spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: layla34*
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect